import pg from 'pg'

export async function createTables(pool: pg.Pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS emotes(
      id VARCHAR(128) PRIMARY KEY,
      name VARCHAR(128) NOT NULL,
      animated BOOLEAN NOT NULL,
      urls JSONB
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS games(
      id INTEGER PRIMARY KEY,
      name VARCHAR(1024) NOT NULL
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS channel_names(
      id INTEGER PRIMARY KEY,
      name VARCHAR(50) NOT NULL UNIQUE
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_names(
      id INTEGER PRIMARY KEY,
      name VARCHAR(50) NOT NULL UNIQUE
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS emote_usage(
      timestamp BIGINT NOT NULL,
      channel_id INTEGER,
      user_id INTEGER,
      emote_id VARCHAR(128),
      count INT,

      CONSTRAINT pk_emotes
        PRIMARY KEY(timestamp, user_id, channel_id, emote_id),

      CONSTRAINT fk_user_names
        FOREIGN KEY(user_id) REFERENCES user_names(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_channel_names
        FOREIGN KEY(channel_id) REFERENCES channel_names(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_emotes
        FOREIGN KEY(emote_id) REFERENCES emotes(id)
        ON DELETE CASCADE
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_channels(
      timestamp BIGINT NOT NULL,
      user_id INTEGER,
      channel_id INTEGER,
      count INTEGER,

      CONSTRAINT pk_user_channels
        PRIMARY KEY(timestamp, user_id, channel_id),

      CONSTRAINT fk_user_names
        FOREIGN KEY(user_id) REFERENCES user_names(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_channel_names
        FOREIGN KEY(channel_id) REFERENCES channel_names(id)
        ON DELETE CASCADE
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS messages(
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      message VARCHAR(500) NOT NULL,
      timestamp BIGINT NOT NULL,
      channel_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      user_name VARCHAR(50) NOT NULL,
      game_id INTEGER NOT NULL,
      subscriber BOOLEAN NOT NULL,
      moderator BOOLEAN NOT NULL,
      turbo BOOLEAN NOT NULL,
      first_message BOOLEAN NOT NULL,

      CONSTRAINT fk_channel
        FOREIGN KEY(channel_id) REFERENCES channel_names(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_user
        FOREIGN KEY(user_id) REFERENCES user_names(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_game
        FOREIGN KEY(game_id) REFERENCES games(id)
        ON DELETE CASCADE
    );
  `)

  await pool.query(`
    CREATE TABLE IF NOT EXISTS emotes_in_messages(
      message_id INTEGER NOT NULL,
      emote_id VARCHAR(128) NOT NULL,
      count INT,

      CONSTRAINT pk_emotes_in_messages
        PRIMARY KEY(message_id, emote_id),

      CONSTRAINT fk_message
        FOREIGN KEY(message_id) REFERENCES messages(id)
        ON DELETE CASCADE,

      CONSTRAINT fk_emote
        FOREIGN KEY(emote_id) REFERENCES emotes(id)
        ON DELETE CASCADE
    );
  `)
}
